name: Forensics Testing
#Testing Fornsics
on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  forensics_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run forensics.py
        run: |
          python forensics.py
